CREATE TABLE PUBLIC.DEPARTMENT
(
    ID   INT         NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NULL,

    PRIMARY KEY (ID)
);


CREATE TABLE PUBLIC.EMPLOYEE
(
    ID            INT         NOT NULL AUTO_INCREMENT,
    NAME          VARCHAR(50) NOT NULL,
    SALARY        DECIMAL(7)  NULL,
    DEPARTMENT_ID INT         NOT NULL,
    MANAGER_ID    INT,

    PRIMARY KEY (ID),

    CONSTRAINT FK_EMPLOYEE_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
            REFERENCES PUBLIC.DEPARTMENT (ID),
    CONSTRAINT FK_EMPLOYEE_EMPLOYEE
        FOREIGN KEY (MANAGER_ID)
            REFERENCES PUBLIC.EMPLOYEE (ID)
);

CREATE INDEX FK_EMPLOYEE_DEPARTMENT_IDX ON PUBLIC.EMPLOYEE (DEPARTMENT_ID ASC);
CREATE INDEX FK_EMPLOYEE_EMPLOYEE_IDX ON PUBLIC.EMPLOYEE (MANAGER_ID ASC);

CREATE TABLE PUBLIC.ADDRESS
(
    ID          INT         NOT NULL AUTO_INCREMENT,
    STREET      VARCHAR(50) NULL,
    HOUSENUMBER VARCHAR(5)  NULL,
    ZIP         VARCHAR(10) NOT NULL,
    CITY        VARCHAR(50) NOT NULL,
    EMPLOYEE_ID INT         NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT FK_ADDRESS_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
            REFERENCES PUBLIC.EMPLOYEE (ID)
);

CREATE INDEX FK_ADDRESS_EMPLOYEE_IDX ON PUBLIC.ADDRESS (EMPLOYEE_ID ASC);

CREATE TABLE PUBLIC.PHONE
(
    ID                     INT         NOT NULL AUTO_INCREMENT,
    TYPE                   VARCHAR(20) NOT NULL,
    NUMBER                 VARCHAR(30) NOT NULL,
    EMPLOYEE_ID            INT         NOT NULL,
    EMPLOYEE_DEPARTMENT_ID INT         NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT FK_PHONE_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
            REFERENCES PUBLIC.EMPLOYEE (ID)
);

CREATE INDEX FK_PHONE_EMPLOYEE_IDX ON PUBLIC.PHONE (EMPLOYEE_ID ASC);
